# -*- coding: utf-8 -*-
"""chroma

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ViLcydjxUlR5KE78aDo910HVluBtf0O5
"""



"""# **Load ChromaDB database**"""

from langchain.vectorstores import Chroma
from langchain_community.vectorstores import Chroma
from langchain.embeddings import HuggingFaceEmbeddings

# Load embedding model
embedding_model = HuggingFaceEmbeddings(model_name= "all-MiniLM-L12-v2")

persist_directory = '/content/drive/MyDrive/...'

vectordb = Chroma.from_documents(
    documents=document,
    embedding=embedding_model,
    persist_directory=persist_directory
)
vectordb.persist()

print(vectordb._collection.count())